-- 코드를 입력하세요
WITH B_T AS (
    SELECT A.AUTHOR_ID, A.AUTHOR_NAME, CATEGORY, PRICE * SALES AS TOTAL_SALES , PRICE, SALES, B.BOOK_ID
    FROM BOOK AS B
    INNER JOIN AUTHOR AS A
    ON B.AUTHOR_ID = A.AUTHOR_ID
    
    INNER JOIN BOOK_SALES AS S
    ON B.BOOK_ID = S.BOOK_ID
    
    WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1
    
    # GROUP BY CATEGORY
    ORDER BY AUTHOR_ID ASC, CATEGORY DESC
    
)

SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(TOTAL_SALES) AS TOTAL_SALES FROM B_T
GROUP BY AUTHOR_ID, AUTHOR_NAME, CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC