# # -- 코드를 작성해주세요
# SELECT ID
# FROM ECOLI_DATA
# WHERE PARENT_ID IN (
#     SELECT ID FROM ECOLI_DATA WHERE PARENT_ID IN ( #2 세대
#         SELECT ID FROM ECOLI_DATA WHERE PARENT_ID IS NULL # 1세대
#     )
# )
# ORDER BY ID

WITH RECURSIVE CTE AS  (
    SELECT ID, PARENT_ID, 1 AS GEN
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E1.ID, E1.PARENT_ID, GEN + 1
    FROM ECOLI_DATA E1
    JOIN CTE 
    ON CTE.ID = E1.PARENT_ID
)

SELECT ID FROM CTE WHERE GEN = 3
ORDER BY ID

