
-- 코드를 작성해주세요
# WITH RECURSIVE EX1 AS (
#     SELECT I.*, PARENT_ITEM_ID, 0 AS GEN
#     FROM ITEM_INFO AS I
#     INNER JOIN ITEM_TREE AS T
#     ON I.ITEM_ID = T.ITEM_ID
#     WHERE T.PARENT_ITEM_ID IS NULL
    
#     UNION ALL
    
#     SELECT I.*, T.PARENT_ITEM_ID, EX1.GEN + 1 AS GEN
#     FROM ITEM_INFO AS I
#     INNER JOIN ITEM_TREE AS T
#     ON I.ITEM_ID = T.ITEM_ID
    
#     INNER JOIN EX1
#     ON EX1.ITEM_ID = T.PARENT_ITEM_ID
    
    
# )

SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO AS I
INNER JOIN ITEM_TREE
USING(ITEM_ID)
WHERE I.ITEM_ID NOT IN (SELECT PARENT_ITEM_ID FROM ITEM_TREE WHERE PARENT_ITEM_ID IS NOT NULL)
ORDER BY 1 DESC