WITH CTE AS (
    SELECT *, RANK () OVER ( ORDER BY SIZE_OF_COLONY DESC)  AS R FROM ECOLI_DATA
    ORDER BY R DESC
)
    
# SELECT * FROM CTE

SELECT ID,
CASE WHEN R <= 0.25 * (SELECT COUNT(ID) FROM ECOLI_DATA) THEN 'CRITICAL'
 WHEN R <= 0.50 * (SELECT COUNT(ID) FROM ECOLI_DATA) THEN 'HIGH'
 WHEN R <= 0.75 * (SELECT COUNT(ID) FROM ECOLI_DATA) THEN 'MEDIUM'
 WHEN R <= (SELECT COUNT(ID) FROM ECOLI_DATA) THEN 'LOW'
END AS COLONY_NAME
FROM CTE
ORDER BY 1

























/*
WITH RANK_DATA AS (
    SELECT ID, SIZE_OF_COLONY, RANK () OVER (ORDER BY SIZE_OF_COLONY DESC) * 100 / COUNT(*) OVER () AS RANK_PERCENT
    FROM ECOLI_DATA
ORDER BY ID
)
SELECT ID,  
CASE
    WHEN RANK_PERCENT <= 25 THEN 'CRITICAL'
    WHEN RANK_PERCENT <= 50 THEN 'HIGH'
    WHEN RANK_PERCENT <= 75 THEN 'MEDIUM'
    ELSE'LOW'
END AS COLONY_NAME
FROM RANK_DATA

ORDER BY ID
*/

/*
WITH CTE AS (
    SELECT ID, RANK () OVER (ORDER BY SIZE_OF_COLONY) AS R
    
    FROM ECOLI_DATA
)

SELECT ID, CASE
    WHEN R > COUNT(*) OVER () * 0.75 THEN 'CRITICAL'
    WHEN R > COUNT(*) OVER () * 0.5 THEN 'HIGH'
    WHEN R > COUNT(*) OVER () * 0.25 THEN 'MEDIUM'
    ELSE 'LOW'
END AS COLONY_NAME

FROM CTE

ORDER BY ID

*/