-- 코드를 입력하세요
WITH INTACT_LIST AS (
    SELECT ANIMAL_ID FROM ANIMAL_INS
    WHERE SEX_UPON_INTAKE LIKE '%INTACT%'
), NET_LIST AS (
    SELECT ANIMAL_ID FROM ANIMAL_OUTS
    WHERE SEX_UPON_OUTCOME LIKE '%Spayed%' OR SEX_UPON_OUTCOME LIKE '%Neutered%'
) , TARGETS AS (
    SELECT B.ANIMAL_ID FROM INTACT_LIST AS B
    INNER JOIN NET_LIST AS A
    ON B.ANIMAL_ID = A.ANIMAL_ID
)

SELECT ANIMAL_ID, ANIMAL_TYPE, NAME FROM ANIMAL_OUTS
WHERE ANIMAL_ID IN (SELECT * FROM TARGETS)
