-- 코드를 입력하세요


WITH user_pool AS (
    SELECT USER_ID FROM USER_INFO WHERE YEAR(JOINED) = 2021
), s_pool AS (
    SELECT s.* FROM ONLINE_SALE AS S
    INNER JOIN user_pool AS u
    ON S.USER_ID = u.USER_ID
) 

SELECT YEAR(sales_date) AS YEAR, MONTH(sales_date) AS MONTH,
COUNT(DISTINCT USER_ID) AS PURCHASED_USERS, 
    ROUND((COUNT(DISTINCT USER_ID) / (SELECT COUNT(DISTINCT USER_ID) FROM USER_POOL)), 1)
     AS PUCHASED_RATIO

FROM s_pool
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH

# SELECT *
# from s_pool
# ORDER BY USER_ID