-- 코드를 입력하세요
WITH REMAIN AS (
    SELECT * FROM ANIMAL_INS
    WHERE ANIMAL_ID NOT IN (SELECT ANIMAL_ID FROM ANIMAL_OUTS)
), R_T AS (
    SELECT NAME, DATETIME
    FROM (SELECT NAME, DATETIME, RANK() OVER (ORDER BY DATETIME ASC) AS R FROM REMAIN ) AS EX
    WHERE R <=3
)

SELECT * FROM R_T
ORDER BY DATETIME