WITH DAYS AS (
    SELECT HISTORY_ID,CAR_ID, DATEDIFF(END_DATE, START_DATE) + 1 AS DAY
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
), D_T AS (
    
    SELECT *,
    CASE WHEN DAY >= 90 THEN '90일 이상'
    WHEN DAY >= 30 THEN '30일 이상'
    WHEN DAY >= 7 THEN '7일 이상'
    ELSE '없음'
    END AS DURATION_TYPE
    FROM DAYS
    
    JOIN CAR_RENTAL_COMPANY_CAR AS C
    
    USING (CAR_ID) 
) ,CTE AS (
    
    SELECT D.*, P.DISCOUNT_RATE
    FROM D_T AS D
    
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
    
    USING (CAR_TYPE, DURATION_TYPE)
)

SELECT HISTORY_ID,  ROUND((DAILY_FEE * DAY) * (100 - ifnull(DISCOUNT_RATE, 0)) * 0.01) AS FEE
FROM CTE WHERE CAR_TYPE LIKE '트럭'
ORDER BY FEE DESC, 1 DESC




















/*
-- 코드를 입력하세요
WITH T AS (
    SELECT *, DATEDIFF(END_DATE, START_DATE) + 1 AS DAYS
    ,((DATEDIFF(END_DATE, START_DATE) + 1) * DAILY_FEE) AS ORIGIN_FEE
    , CASE 
    WHEN (DATEDIFF(END_DATE, START_DATE) + 1) >= 90 THEN '90일 이상'        WHEN (DATEDIFF(END_DATE, START_DATE) + 1) >= 30 THEN '30일 이상' 
    WHEN (DATEDIFF(END_DATE, START_DATE) + 1) >= 7 THEN '7일 이상'
    END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
    INNER JOIN CAR_RENTAL_COMPANY_CAR AS C
    USING (CAR_ID)
    WHERE CAR_TYPE = '트럭'
), T2 AS (
    SELECT T.*, DISCOUNT_RATE FROM T
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
    ON T.DURATION_TYPE = P.DURATION_TYPE AND P.CAR_TYPE = '트럭'
)
# SELECT * FROM T2
SELECT HISTORY_ID,
ROUND(ORIGIN_FEE / 100 * (100 - IFNULL(DISCOUNT_RATE, 0) )) AS FEE FROM T2
ORDER BY 2 DESC, 1 DESC
*/