-- 코드를 입력하세요
WITH T AS (
    SELECT *, DATEDIFF(END_DATE, START_DATE) + 1 AS DAYS
    ,((DATEDIFF(END_DATE, START_DATE) + 1) * DAILY_FEE) AS ORIGIN_FEE
    , CASE 
    WHEN (DATEDIFF(END_DATE, START_DATE) + 1) >= 90 THEN '90일 이상'        WHEN (DATEDIFF(END_DATE, START_DATE) + 1) >= 30 THEN '30일 이상' 
    WHEN (DATEDIFF(END_DATE, START_DATE) + 1) >= 7 THEN '7일 이상'
    END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
    INNER JOIN CAR_RENTAL_COMPANY_CAR AS C
    USING (CAR_ID)
    WHERE CAR_TYPE = '트럭'
), T2 AS (
    SELECT T.*, DISCOUNT_RATE FROM T
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
    ON T.DURATION_TYPE = P.DURATION_TYPE AND P.CAR_TYPE = '트럭'
)
# SELECT * FROM T2
SELECT HISTORY_ID,
ROUND(ORIGIN_FEE / 100 * (100 - IFNULL(DISCOUNT_RATE, 0) )) AS FEE FROM T2
ORDER BY 2 DESC, 1 DESC