-- 코드를 입력하세요
SELECT A.APNT_NO, PT_NAME, PT_NO, D.MCDP_CD, D.DR_NAME, A.APNT_YMD 

FROM PATIENT AS P
JOIN APPOINTMENT AS A
USING (PT_NO)
JOIN DOCTOR AS D
ON A.MDDR_ID = D.DR_ID

WHERE APNT_YMD LIKE '2022-04-13%'
AND APNT_CNCL_YN = 'N'

ORDER BY APNT_YMD