# -- 코드를 입력하세요

# WITH RECURSIVE T AS(
#     SELECT 0 AS HOUR
    
#     UNION ALL

#     SELECT HOUR + 1 FROM T
#     WHERE HOUR < 23
# )

# # SELECT *, HOUR(DATETIME) FROM ANIMAL_OUTS
# # ORDER BY HOUR(DATETIME)

# SELECT HOUR, COUNT(A.DATETIME) AS COUNT
# FROM T  
# LEFT JOIN ANIMAL_OUTS AS A 
# ON T.HOUR = HOUR(A.DATETIME) 
# GROUP BY HOUR
# ORDER BY HOUR

WITH RECURSIVE H AS (
    SELECT 0 AS HOUR
    
    UNION ALL
    
    SELECT H.HOUR + 1 AS HOUR
    FROM H
    WHERE H.HOUR < 23
)

SELECT HOUR, COUNT(ANIMAL_ID) AS COUNT FROM H

LEFT JOIN ANIMAL_OUTS
ON H.HOUR = HOUR(DATETIME)
GROUP BY HOUR