-- 코드를 작성해주세요




WITH ID AS (

SELECT ITEM_ID FROM ITEM_TREE
WHERE PARENT_ITEM_ID IN (SELECT ITEM_ID FROM ITEM_INFO WHERE RARITY = 'RARE')
UNION
SELECT ITEM_ID FROM (SELECT ITEM_ID FROM ITEM_INFO WHERE RARITY = 'RARE') AS I
WHERE ITEM_ID NOT IN (SELECT PARENT_ITEM_ID FROM ITEM_TREE WHERE PARENT_ITEM_ID IS NOT NULL)
    )

SELECT ITEM_ID, ITEM_NAME, RARITY FROM ITEM_INFO
WHERE ITEM_ID IN (SELECT ITEM_ID FROM ID) ORDER BY 1 DESC