-- 코드를 입력하세요
# 2022 08 ~ 10 / 대여횟수 >= 5 
# 월별 자동차 1d별 총 대여횟수(시작일) (c: RECORDS) 0 이면 제거
# 월 acs, id desc

# SELECT * FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY ORDER BY CAR_ID, START_DATE

# SELECT MONTH(START_DATE), CAR_ID
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE
#     YEAR(START_DATE) = 2022 AND MONTH(START_DATE) BETWEEN 8 AND 10
# ORDER BY MONTH(START_DATE), CAR_ID DESC    

# SELECT MONTH(START_DATE) AS MONTH, CAR_ID
# , COUNT(CAR_ID) AS RECORDS 
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE
#     YEAR(START_DATE) = 2022 AND MONTH(START_DATE) BETWEEN 8 AND 10
# GROUP BY CAR_ID, MONTH
# HAVING RECORDS >= 5
# ORDER BY MONTH, CAR_ID DESC

WITH T AS (
    SELECT MONTH(START_DATE) AS MONTH, CAR_ID
    , COUNT(CAR_ID) AS RECORDS 
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE
        YEAR(START_DATE) = 2022 AND MONTH(START_DATE) BETWEEN 8 AND 10
        AND CAR_ID IN (
            SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
            WHERE YEAR(START_DATE) = 2022 AND MONTH(START_DATE) BETWEEN 8 AND 10
            GROUP BY CAR_ID
            HAVING COUNT(*) >= 5
        )
    GROUP BY CAR_ID, MONTH
    ORDER BY MONTH, CAR_ID DESC
)

SELECT * FROM T 
