-- 코드를 작성해주세요

WITH FISH_LIST AS (
    SELECT COUNT(*) AS FISH_COUNT, FISH_TYPE, AVG(IFNULL(LENGTH, 10)) AS AVG_LENGTH FROM FISH_INFO    
    GROUP BY FISH_TYPE
    HAVING AVG_LENGTH >= 33
), FISH_RANK AS (
    SELECT * FROM (
        SELECT ID,
        FISH_TYPE ,
        LENGTH,
        RANK() OVER (PARTITION BY FISH_TYPE ORDER BY LENGTH DESC) AS R
        FROM FISH_INFO
    ) AS EX
    WHERE R = 1
)

SELECT FISH_COUNT, LENGTH AS MAX_LENGTH, L.FISH_TYPE
FROM FISH_LIST AS L
INNER JOIN FISH_RANK AS R
ON L.FISH_TYPE = R.FISH_TYPE

